name: helm ci
on:
  pull_request:
    paths:
      - '.github/workflows/on_pull_request_helm.yaml'
      - 'Earthfile'
      - 'charts/**'

jobs:
  ci-helm:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: wistia/parse-tool-versions@v1.0

      - uses: earthly/actions-setup@v1
        with: { version: "v${{ env.EARTHLY_TOOL_VERSION }}" }

      - run: |
          earthly \
            +ci-helm \
            --HELM_VERSION=${{ env.HELM_TOOL_VERSION }} \
            --CHART_TESTING_VERSION=${{ env.HELM-CT_TOOL_VERSION }} \
            --KUBECONFORM_VERSION=${{ env.KUBECONFORM_TOOL_VERSION }}
